-- SPDX-License-Identifier: Apache-2.0
-- Copyright 2026 Aaron K. Clark
-- Deduplicate opportunities across Lead, Ready, and Pipeline stages (#269).
-- Removes orphan duplicate lead rows where the opportunity has already progressed
-- to ready/pipeline, and purges duplicate lead rows generated by re-posted listings.

-- 1. Remove lead rows when the opportunity already exists in ready or pipeline
DELETE FROM applications
WHERE status = 'lead'
  AND EXISTS (
      SELECT 1 FROM applications other
      WHERE other.tenant_id = applications.tenant_id
        AND other.id != applications.id
        AND other.status != 'lead'
        AND (
            (applications.link != '' AND other.link = applications.link)
            OR (
                lower(trim(other.company)) = lower(trim(applications.company))
                AND lower(trim(other.role)) = lower(trim(applications.role))
            )
        )
  );

-- 2. Deduplicate duplicate lead rows among themselves (keeping the oldest row)
DELETE FROM applications
WHERE status = 'lead'
  AND EXISTS (
      SELECT 1 FROM applications earlier
      WHERE earlier.tenant_id = applications.tenant_id
        AND earlier.status = 'lead'
        AND earlier.id < applications.id
        AND (
            (applications.link != '' AND earlier.link = applications.link)
            OR (
                lower(trim(earlier.company)) = lower(trim(applications.company))
                AND lower(trim(earlier.role)) = lower(trim(applications.role))
            )
        )
  );
